### ISSUE TITLE
Enable visualization of multiband rasters (for example rgb) 

### ISSUE THREAD

**Issue by ac-willeke** [NINAnor/naturregnskap_maps_uploader#1]
Currently only single-band COGs are supported, enable to be able to handle both single- and multiband.

**Comment by nicokant** [comment]
multi band raster are handled by default with titiler, you need to choose all the bands `bidx=0&bidx=1&bidx=2&bidx=3`. Always include an alpha band to avoid black background appearing if the raster has nodata values
